export const CREATE_DISH_REQUEST = "CREATE_DISH_REQUEST";
export const CREATE_DISH_SUCCESS = "CREATE_DISH_SUCCESS";
export const CREATE_DISH_FAILED = "CREATE_DISH_FAILED";
export const CREATE_DISH_RESET = "CREATE_DISH_RESET";

export const DELETE_DISH_REQUEST = "DELETE_DISH_REQUEST";
export const DELETE_DISH_SUCCESS = "DELETE_DISH_SUCCESS";
export const DELETE_DISH_FAILED = "DELETE_DISH_FAILED";
export const DELETE_DISH_RESET = "DELETE_DISH_RESET";

export const UPDATE_DISH_REQUEST = "UPDATE_DISH_REQUEST";
export const UPDATE_DISH_SUCCESS = "UPDATE_DISH_SUCCESS";
export const UPDATE_DISH_FAILED = "UPDATE_DISH_FAILED";
export const UPDATE_DISH_RESET = "UPDATE_DISH_RESET";

export const DISHES_LOADING = "DISHES_LOADING";
export const DISHES_FAILED = "DISHES_FAILED";
export const ADD_DISHES = "ADD_DISHES";

export const DISH_LIST_REQUEST = "DISH_LIST_REQUEST";
export const DISH_LIST_SUCCESS = "DISH_LIST_SUCCESS";
export const DISH_LIST_FAILED = "DISH_LIST_FAILED";
