export const ADD_COMMENT = "ADD_COMMENT";
export const DISHES_LOADING = "DISHES_LOADING";
export const DISHES_FAILED = "DISHES_FAILED";

export const ADD_DISHES = "ADD_DISHES";
export const ADD_COMMENTS = "ADD_COMMENTS";
export const COMMENTS_FAILED = "COMMENTS_FAILED";

export const PROMOS_LOADING = "PROMOS_LOADING";
export const ADD_PROMOS = "ADD_PROMOS";
export const PROMOS_FAILED = "PROMOS_FAILED";

export const LEADERS_LOADING = "LEADERS_LOADING";
export const ADD_LEADERS = "ADD_LEADERS";
export const LEADERS_FAILED = "LEADERS_FAILED";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const FAVORITES_LOADING = "FAVORITES_LOADING";
export const FAVORITES_FAILED = "FAVORITES_FAILED";
export const ADD_FAVORITES = "ADD_FAVORITES";

export const CREATE_DISH_REQUEST = "CREATE_DISH_REQUEST";
export const CREATE_DISH_SUCCESS = "CREATE_DISH_SUCCESS";
export const CREATE_DISH_FAILED = "CREATE_DISH_FAILED";
export const CREATE_DISH_RESET = "CREATE_DISH_RESET";

export const DELETE_DISH_REQUEST = "DELETE_DISH_REQUEST";
export const DELETE_DISH_SUCCESS = "DELETE_DISH_SUCCESS";
export const DELETE_DISH_FAILED = "DELETE_DISH_FAILED";
export const DELETE_DISH_RESET = "DELETE_DISH_RESET";

export const UPDATE_DISH_REQUEST = "UPDATE_DISH_REQUEST";
export const UPDATE_DISH_SUCCESS = "UPDATE_DISH_SUCCESS";
export const UPDATE_DISH_FAILED = "UPDATE_DISH_FAILED";
export const UPDATE_DISH_RESET = "UPDATE_DISH_RESET";
